# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ykcyX3njMIAYMyezmvD3KSaPzXIHNb2
"""



import streamlit as st
import pandas as pd
import joblib

joblib.load("model_test.pkl")

age = st.number_input("Age" , max_value = 90 , min_value = 1 , value = 18)
sex = st.selectbox("sex" , ["F" , "M"])
situation = st.selectbox("situation" , ["virgin" , "not virgin"])
skin_color = st.selectbox("skin" , ["white" , "yellow" ,"black"])
weight = st.number_input("weight" , max_value = 100 , min_value = 20 , value = 20)
Height = st.number_input("Height" , max_value = 200 , min_value = 100 , value = 100)
beauty = st.slider("beauty on 10" , 0,10,7)

sex_num = 0 if sex == "M" else 1
skin_black = 1 if skin_color == "black" else 0
skin_white = 1 if skin_color == "white" else 0
skin_yellow = 1 if skin_color == "yellow" else 0

input = {
    "age" : age,
    "sex" : sex,
    "situation" : situation,
     "skin_black": [skin_black],
    "skin_white": [skin_white],
    "skin_yellow": [skin_yellow],
    "weight" : weight,
    "Height" : Height,
    "beauty" : beauty
}
df = pd.DataFrame(input , index = [0])

if st.button("Predict Price"):
    price_pred = model.predict(input)[0]
    st.success(f"Predicted Price: ${price_pred:.2f}")

